### ISSUE TITLE
How to install it in our org as a component and use it

### ISSUE THREAD

**Issue by tetradev01** [Justin1108/sfdc-lexforce#2]
Hi Justin,

I cannot find any documentation on how to use it and install it in out org, I have seen you blog too but it explains only after we have installed it. Can you please provide some steps on how to start using it.

Thanks,

**Comment by Justin1108** [comment]
There're multiple ways to deploy it. You should download the files to your local computer first. After that you can deploy them to your org either by Eclipse or Force.com migration tool.
