### ISSUE TITLE
Unit Test Coverage?

### ISSUE THREAD

**Issue by rmccu** [Justin1108/sfdc-lexforce#4]
There is no unit test coverage for LexForceComponentCtrl.

**Comment by Justin1108** [comment]
Test class is added. Thanks for bringing it up.

**Comment by rmccu** [comment]
Thank you very much. Could I make a suggestion? I get an exception with this line:
ctrl.fieldName = 'CleanStatus';
Could we change it to:
ctrl.fieldName = 'Salutation';

I think the issue is that 'CleanStatus' does not exist for all orgs.

**Comment by Justin1108** [comment]
Thx! I updated my code.
